In [1]:
import numpy as np

## Datatypes and attributes

In [2]:
# Numpy main data type is nd-array
a1= np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [14]:
a2= np.array([[2.0,3,4],
              [3.4,42.0,52.2]])



a3 = np.array([[4, 25, 543],
               [24, 53, 24],
               [4,53,2]])

In [15]:
a3.shape

(3, 3)

In [16]:
a1.ndim, a2.ndim

(1, 2)

In [17]:
a3.ndim

2

In [18]:
a1.dtype

dtype('int64')

In [19]:
a2.dtype

dtype('float64')

In [20]:
a1.size, a2.size

(3, 6)

In [21]:
type(a1)

numpy.ndarray

In [22]:
# create a dataframe from numpy array
import pandas as pd 

df= pd.DataFrame(a2)
df

0     1     2
0  2.0   3.0   4.0
1  3.4  42.0  52.2

##creatinn array 

In [28]:
ones = np.ones((3,4))

In [29]:
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
ones.dtype

dtype('float64')

In [31]:
type(ones)

numpy.ndarray

In [32]:
zeros = np.zeros((4,5))

In [33]:
zeros


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
range_array = np.arange(0,12,3)

In [36]:
range_array

array([0, 3, 6, 9])

In [37]:
random_array = np.random.randint(0,10,size=(3,5))

In [38]:
random_array

array([[1, 2, 7, 5, 6],
       [2, 1, 6, 6, 9],
       [8, 1, 8, 8, 3]])

In [39]:
random_array.size

15

In [40]:
np.random.random((4,5))

array([[0.8741871 , 0.02968693, 0.38952307, 0.57782992, 0.24426568],
       [0.98902442, 0.62495066, 0.06027782, 0.4491449 , 0.93401986],
       [0.71724848, 0.61486214, 0.88409195, 0.70430269, 0.60959432],
       [0.15593837, 0.71717322, 0.41499438, 0.29863013, 0.86126681]])

In [41]:
random_array2= np.random.rand(2,3)
random_array2

array([[0.7013175 , 0.25196048, 0.77112894],
       [0.63358903, 0.04318082, 0.41509186]])

In [46]:
#pseudo-random numbers
np.random.seed(seed=0)
random_array3 = np.random.randint(10, size=(5,3))

In [50]:
random_array3

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [53]:
np.random.seed(7)
random_array5= np.random.random((5,3))
random_array5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [54]:
random_array5= np.random.random((5,3))
random_array5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

# 3.  Viewing arrays and matrices

In [55]:
np.unique(random_array5)

array([0.02489923, 0.13316945, 0.21338535, 0.23030288, 0.45212396,
       0.46775286, 0.52341258, 0.54848992, 0.60054892, 0.66901324,
       0.75040986, 0.90912837, 0.90959353, 0.93120602, 0.9501295 ])

In [56]:
np.unique(random_array)

array([1, 2, 3, 5, 6, 7, 8, 9])

In [57]:
random_array5[0]

array([0.90959353, 0.21338535, 0.45212396])

In [58]:
random_array.shape

(3, 5)

In [61]:
#it gives array of two aheading element
random_array[:2, :2]

array([[1, 2],
       [2, 1]])

In [64]:
#4-D
a4= np.random.randint(10, size=(3,4,5,6))
a4

array([[[[6, 8, 5, 4, 3, 0],
         [7, 4, 0, 8, 5, 0],
         [7, 5, 1, 5, 9, 4],
         [1, 9, 6, 5, 6, 8],
         [5, 9, 4, 6, 0, 6]],

        [[2, 3, 1, 6, 7, 0],
         [0, 4, 7, 0, 2, 9],
         [6, 1, 2, 2, 8, 9],
         [7, 2, 4, 7, 7, 9],
         [1, 0, 1, 8, 7, 4]],

        [[6, 1, 4, 8, 7, 3],
         [3, 6, 4, 9, 5, 7],
         [9, 9, 7, 6, 9, 8],
         [8, 6, 2, 2, 2, 5],
         [1, 4, 1, 4, 9, 5]],

        [[3, 5, 8, 7, 0, 8],
         [5, 4, 0, 4, 7, 0],
         [6, 1, 0, 7, 6, 0],
         [3, 6, 7, 4, 8, 7],
         [9, 6, 3, 9, 2, 5]]],


       [[[4, 1, 1, 5, 1, 2],
         [1, 7, 1, 2, 8, 6],
         [5, 6, 8, 3, 2, 1],
         [5, 0, 4, 3, 7, 4],
         [4, 0, 5, 2, 5, 6]],

        [[9, 6, 7, 5, 7, 4],
         [8, 7, 7, 8, 3, 3],
         [7, 0, 0, 6, 7, 0],
         [2, 7, 4, 2, 5, 8],
         [0, 5, 3, 4, 5, 8]],

        [[0, 5, 9, 3, 5, 0],
         [1, 7, 7, 7, 2, 3],
         [6, 4, 8, 2, 7, 5],
         [7, 2, 9, 3, 0, 2],


In [63]:
a4.shape

(3, 4, 5, 6)

In [65]:
#get the first four numbers of the innermost arrays

In [66]:
a4[:, :,:,:4]

array([[[[6, 8, 5, 4],
         [7, 4, 0, 8],
         [7, 5, 1, 5],
         [1, 9, 6, 5],
         [5, 9, 4, 6]],

        [[2, 3, 1, 6],
         [0, 4, 7, 0],
         [6, 1, 2, 2],
         [7, 2, 4, 7],
         [1, 0, 1, 8]],

        [[6, 1, 4, 8],
         [3, 6, 4, 9],
         [9, 9, 7, 6],
         [8, 6, 2, 2],
         [1, 4, 1, 4]],

        [[3, 5, 8, 7],
         [5, 4, 0, 4],
         [6, 1, 0, 7],
         [3, 6, 7, 4],
         [9, 6, 3, 9]]],


       [[[4, 1, 1, 5],
         [1, 7, 1, 2],
         [5, 6, 8, 3],
         [5, 0, 4, 3],
         [4, 0, 5, 2]],

        [[9, 6, 7, 5],
         [8, 7, 7, 8],
         [7, 0, 0, 6],
         [2, 7, 4, 2],
         [0, 5, 3, 4]],

        [[0, 5, 9, 3],
         [1, 7, 7, 7],
         [6, 4, 8, 2],
         [7, 2, 9, 3],
         [9, 9, 4, 3]],

        [[3, 8, 4, 8],
         [2, 8, 5, 0],
         [1, 1, 4, 1],
         [9, 6, 9, 9],
         [1, 5, 6, 2]]],


       [[[1, 6, 0, 0],
         [7, 4, 2, 6],
         [7, 3

## 4, Manipulating and comparing arrays

## arithetic 

In [67]:
a1


array([1, 2, 3])

In [68]:
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [69]:
ones=np.ones(3)

In [70]:
ones

array([1., 1., 1.])

In [71]:
a1+ones

array([2., 3., 4.])

In [72]:
a1-ones

array([0., 1., 2.])

In [73]:
a1*ones

array([1., 2., 3.])

In [74]:
a2

array([[ 2. ,  3. ,  4. ],
       [ 3.4, 42. , 52.2]])

In [75]:
a1*a2

array([[  2. ,   6. ,  12. ],
       [  3.4,  84. , 156.6]])

In [76]:
a3

array([[  4,  25, 543],
       [ 24,  53,  24],
       [  4,  53,   2]])

In [77]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [78]:
a1/ones

array([1., 2., 3.])

In [79]:
#floor division remives the decimal
a1//ones

array([1., 2., 3.])

In [80]:
a2/a1


array([[ 2.        ,  1.5       ,  1.33333333],
       [ 3.4       , 21.        , 17.4       ]])

In [81]:
a2//a1

array([[ 2.,  1.,  1.],
       [ 3., 21., 17.]])

In [82]:
a2 ** 2

array([[   4.  ,    9.  ,   16.  ],
       [  11.56, 1764.  , 2724.84]])

In [83]:
np.square(a2)

array([[   4.  ,    9.  ,   16.  ],
       [  11.56, 1764.  , 2724.84]])

In [84]:
a2 % 2

array([[0. , 1. , 0. ],
       [1.4, 0. , 0.2]])

In [85]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [86]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

## Aggreation

In [87]:
listy_list = [1,2,3]
type(listy_list)

list

In [88]:
sum(listy_list)

6

In [89]:
a1

array([1, 2, 3])

In [90]:
type(a1)

numpy.ndarray

In [91]:
sum(a1)

6

In [92]:
np.sum(a1)

6

In [93]:
# what is the main difference between

# Use python's methods(sum()) on python datatypes and use 
# NumPy's methods on Numpy arrays(np.sum()).

In [94]:
#creating a massive array
massive_array = np.random.random(100000)
massive_array

array([0.16403321, 0.01471861, 0.50665503, ..., 0.55362358, 0.83488456,
       0.04494427])

In [95]:
%timeit sum(massive_array) #python's sum()
%timeit np.sum(massive_array) # Numpy's sum()

7.25 ms ± 69.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
21.7 µs ± 24.4 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [96]:
np.mean(a2)

17.766666666666666

In [98]:
np.max(a2)

52.2

In [99]:
np.std(a2)

20.95818588417317

In [100]:
np.var(a2)

439.24555555555554

### Reshaping and transposing 

In [102]:
a2


array([[ 2. ,  3. ,  4. ],
       [ 3.4, 42. , 52.2]])

In [103]:
a3

array([[  4,  25, 543],
       [ 24,  53,  24],
       [  4,  53,   2]])

In [104]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [105]:
a2.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [106]:
a2=np.array([[2,3],
            [2,4],[4,6]])

In [107]:
a2.shape

(3, 2)

In [108]:
a2*a3


ValueError: operands could not be broadcast together with shapes (3,2) (3,3) 

In [109]:
a3=np.array([[4,5,5],[35,5,2]])

In [110]:
a3

array([[ 4,  5,  5],
       [35,  5,  2]])

In [111]:
a2*a3

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [112]:
a2_reshape= a2.reshape(2,3)

In [113]:
a2_reshape

array([[2, 3, 2],
       [4, 4, 6]])

In [114]:
a2_reshape*a3

array([[  8,  15,  10],
       [140,  20,  12]])

In [115]:
#Transpose
a2.T

array([[2, 2, 4],
       [3, 4, 6]])

In [116]:
a2

array([[2, 3],
       [2, 4],
       [4, 6]])

## Dot product

In [117]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))
mat1
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [118]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [119]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [120]:
# Element wise multiplication hadamard product
mat1*mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [122]:
# DOt product
np.dot(mat1,mat2.T)

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

## DOt Product example (nut butter sales)

In [123]:
np.random.seed(0)
#Number of jars sold
sales_amount = np.random.randint(20,size=(5,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [124]:
#  creeate weekly_sales distribution
weekly_sales = pd.DataFrame(sales_amount, index=["Mon","Tue", "Wed","Thurs","Fri"] ,columns=["Almond butter", "Peanut butter", "cashew Butter"])

In [125]:
weekly_sales

Almond butter  Peanut butter  cashew Butter
Mon               12             15              0
Tue                3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [126]:
#create prices array
prices = np.array([10,8,3])
prices

array([10,  8,  3])

In [127]:
#create butter_prices data frame
butter_prices = pd.DataFrame(prices.reshape(1,3),index=["prices"],columns=["Almond butter", "Peanut butter", "cashew Butter"])

In [128]:
butter_prices

Almond butter  Peanut butter  cashew Butter
prices             10              8              3

In [129]:
total_sales = prices.dot(sales_amount.T)

In [130]:
total_sales

array([240,  75, 296, 124,  79])

In [131]:
#create daily sales
butter_prices

Almond butter  Peanut butter  cashew Butter
prices             10              8              3

In [132]:
weekly_sales

Almond butter  Peanut butter  cashew Butter
Mon               12             15              0
Tue                3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [133]:
daily_sales = butter_prices.dot(weekly_sales.T)

In [134]:
daily_sales

Mon  Tue  Wed  Thurs  Fri
prices  240   75  296    124   79

In [136]:
weekly_sales["Total ($)"]=daily_sales.T
weekly_sales

Almond butter  Peanut butter  cashew Butter  Total ($)
Mon               12             15              0        240
Tue                3              3              7         75
Wed                9             19             18        296
Thurs              4              6             12        124
Fri                1              6              7         79

### Comparision operator

In [137]:
a1

array([1, 2, 3])

In [138]:
a2

array([[2, 3],
       [2, 4],
       [4, 6]])

In [139]:
a2=a2.T

In [140]:
a2

array([[2, 2, 4],
       [3, 4, 6]])

In [141]:
a1>a2

array([[False, False, False],
       [False, False, False]])

In [143]:
bool_arrat=a1>=a2

In [144]:
bool_arrat

array([[False,  True, False],
       [False, False, False]])

In [145]:
bool_arrat.dtype

dtype('bool')

In [146]:
a1>5

array([False, False, False])

## 5. Sorting array

In [147]:
random_array = np.random.randint(10,size=(3,5))

In [148]:
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [149]:
np.sort(random_array)

array([[1, 5, 7, 8, 9],
       [0, 3, 4, 8, 9],
       [0, 2, 3, 3, 5]])

In [150]:
#index sorting according to number at that place
np.argsort(random_array)

array([[2, 3, 0, 1, 4],
       [4, 3, 2, 0, 1],
       [2, 3, 0, 4, 1]])

In [151]:
np.argmin(a1)

0

In [152]:
a1

array([1, 2, 3])

In [153]:
np.argmax(a1)

2

In [154]:
np.argmax(random_array)

4

In [155]:
np.argmax(random_array, axis=0)

array([1, 1, 1, 0, 0])

In [156]:
#axis=0 is y axis axis =1 is x-axis

## 6 .practical actions of Numpy

<img src="images/pandas.png"/> 

In [168]:
# Turn an images into a NumPy array
from matplotlib.image import imread

panda = imread("images/pandas.png")
print(type(panda))

<class 'numpy.ndarray'>


In [169]:
panda

array([[[1.       , 1.       , 1.       , 1.       ],
        [1.       , 1.       , 1.       , 1.       ],
        [1.       , 1.       , 1.       , 1.       ],
        ...,
        [0.9019608, 0.9019608, 0.9019608, 1.       ],
        [0.9019608, 0.9019608, 0.9019608, 1.       ],
        [0.9019608, 0.9019608, 0.9019608, 1.       ]],

       [[1.       , 1.       , 1.       , 1.       ],
        [1.       , 1.       , 1.       , 1.       ],
        [1.       , 1.       , 1.       , 1.       ],
        ...,
        [0.9019608, 0.9019608, 0.9019608, 1.       ],
        [0.9019608, 0.9019608, 0.9019608, 1.       ],
        [0.9019608, 0.9019608, 0.9019608, 1.       ]],

       [[1.       , 1.       , 1.       , 1.       ],
        [1.       , 1.       , 1.       , 1.       ],
        [1.       , 1.       , 1.       , 1.       ],
        ...,
        [0.9019608, 0.9019608, 0.9019608, 1.       ],
        [0.9019608, 0.9019608, 0.9019608, 1.       ],
        [0.9019608, 0.9019608, 0.901960

In [170]:
panda.size, panda.shape, panda.ndim

(3614400, (1004, 900, 4), 3)

In [171]:
panda[:10]

array([[[1.       , 1.       , 1.       , 1.       ],
        [1.       , 1.       , 1.       , 1.       ],
        [1.       , 1.       , 1.       , 1.       ],
        ...,
        [0.9019608, 0.9019608, 0.9019608, 1.       ],
        [0.9019608, 0.9019608, 0.9019608, 1.       ],
        [0.9019608, 0.9019608, 0.9019608, 1.       ]],

       [[1.       , 1.       , 1.       , 1.       ],
        [1.       , 1.       , 1.       , 1.       ],
        [1.       , 1.       , 1.       , 1.       ],
        ...,
        [0.9019608, 0.9019608, 0.9019608, 1.       ],
        [0.9019608, 0.9019608, 0.9019608, 1.       ],
        [0.9019608, 0.9019608, 0.9019608, 1.       ]],

       [[1.       , 1.       , 1.       , 1.       ],
        [1.       , 1.       , 1.       , 1.       ],
        [1.       , 1.       , 1.       , 1.       ],
        ...,
        [0.9019608, 0.9019608, 0.9019608, 1.       ],
        [0.9019608, 0.9019608, 0.9019608, 1.       ],
        [0.9019608, 0.9019608, 0.901960

<img src="images/car.png"/>

In [172]:
car= imread("images/car.png")
print(type(car))


<class 'numpy.ndarray'>


In [173]:
car

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       ...,

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0.

In [174]:
car[:6]

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
  